-- SERVIAUTO database foundation
create extension if not exists pgcrypto;
create table if not exists public.shops(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text,address text,created_at timestamptz default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,shop_id uuid references public.shops(id) on delete set null,full_name text,role text not null default 'owner' check(role in('owner','manager','service_advisor','technician')),created_at timestamptz default now());
create table if not exists public.customers(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,name text not null,phone text,email text,address text,notes text,created_at timestamptz default now());
create table if not exists public.vehicles(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,customer_id uuid not null references public.customers(id) on delete cascade,vin text,year int,make text,model text,trim text,engine text,mileage int default 0,license_plate text,created_at timestamptz default now());
create table if not exists public.repair_orders(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,ro_number text not null,customer_id uuid references public.customers(id) on delete set null,vehicle_id uuid references public.vehicles(id) on delete set null,status text not null default 'open',complaint text,diagnosis text,subtotal numeric(12,2) default 0,tax numeric(12,2) default 0,discount numeric(12,2) default 0,total numeric(12,2) default 0,created_at timestamptz default now());
create table if not exists public.inspections(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,vehicle_id uuid references public.vehicles(id) on delete set null,repair_order_id uuid references public.repair_orders(id) on delete set null,technician_id uuid references public.profiles(id) on delete set null,status text default 'open',notes text,created_at timestamptz default now());
create table if not exists public.inspection_items(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,inspection_id uuid not null references public.inspections(id) on delete cascade,category text not null,item text not null,result text default 'not_checked' check(result in('pass','fail','attention','not_checked')),measurement text,notes text);
create table if not exists public.diagnostic_scans(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,vehicle_id uuid references public.vehicles(id) on delete set null,repair_order_id uuid references public.repair_orders(id) on delete set null,tool_name text,scan_data jsonb default '{}'::jsonb,created_at timestamptz default now());
create table if not exists public.diagnostic_codes(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,scan_id uuid references public.diagnostic_scans(id) on delete set null,code text not null,description text,confirmed boolean default false,created_at timestamptz default now());
create table if not exists public.diagnoses(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,repair_order_id uuid references public.repair_orders(id) on delete set null,code_id uuid references public.diagnostic_codes(id) on delete set null,finding text not null,confidence text default 'possible' check(confidence in('possible','confirmed')),created_at timestamptz default now());
create table if not exists public.parts(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,part_number text,name text not null,manufacturer text,oem_number text,price numeric(12,2),supplier text,availability text,created_at timestamptz default now());
create table if not exists public.inventory(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,part_id uuid not null references public.parts(id) on delete cascade,quantity numeric(12,2) default 0,reorder_level numeric(12,2) default 0,updated_at timestamptz default now());
create table if not exists public.repair_order_items(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,repair_order_id uuid not null references public.repair_orders(id) on delete cascade,part_id uuid references public.parts(id) on delete set null,description text not null,item_type text not null check(item_type in('labor','part','fee')),quantity numeric(12,2) default 1,unit_price numeric(12,2) default 0,total numeric(12,2) default 0);
create table if not exists public.estimates(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,customer_id uuid references public.customers(id) on delete set null,vehicle_id uuid references public.vehicles(id) on delete set null,repair_order_id uuid references public.repair_orders(id) on delete set null,status text default 'draft',subtotal numeric(12,2) default 0,tax numeric(12,2) default 0,total numeric(12,2) default 0,approved_at timestamptz,created_at timestamptz default now());
create table if not exists public.invoices(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,repair_order_id uuid references public.repair_orders(id) on delete set null,invoice_number text not null,status text default 'open',total numeric(12,2) default 0,balance numeric(12,2) default 0,created_at timestamptz default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,invoice_id uuid references public.invoices(id) on delete set null,provider text,provider_payment_id text,amount numeric(12,2) not null,status text default 'recorded',created_at timestamptz default now());
create table if not exists public.customer_followups(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.shops(id) on delete cascade,customer_id uuid references public.customers(id) on delete cascade,vehicle_id uuid references public.vehicles(id) on delete set null,kind text not null,scheduled_for timestamptz,sent_at timestamptz,notes text);
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),shop_id uuid references public.shops(id) on delete cascade,actor_id uuid references auth.users(id) on delete set null,action text not null,entity text,entity_id uuid,metadata jsonb default '{}'::jsonb,created_at timestamptz default now());
create index if not exists customers_shop_idx on public.customers(shop_id);
create index if not exists vehicles_shop_idx on public.vehicles(shop_id);
create index if not exists vehicles_vin_idx on public.vehicles(vin);
create index if not exists repair_orders_shop_idx on public.repair_orders(shop_id);
create index if not exists diagnostic_codes_shop_idx on public.diagnostic_codes(shop_id);
create or replace function public.current_shop_id() returns uuid language sql stable security definer set search_path=public as $$ select shop_id from public.profiles where id=auth.uid() $$;
alter table public.shops enable row level security;
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.vehicles enable row level security;
alter table public.repair_orders enable row level security;
alter table public.inspections enable row level security;
alter table public.inspection_items enable row level security;
alter table public.diagnostic_scans enable row level security;
alter table public.diagnostic_codes enable row level security;
alter table public.diagnoses enable row level security;
alter table public.parts enable row level security;
alter table public.inventory enable row level security;
alter table public.repair_order_items enable row level security;
alter table public.estimates enable row level security;
alter table public.invoices enable row level security;
alter table public.payments enable row level security;
alter table public.customer_followups enable row level security;
alter table public.audit_logs enable row level security;
drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for select using(id=auth.uid());
drop policy if exists shops_member on public.shops;
create policy shops_member on public.shops for select using(id=public.current_shop_id());
do $$ declare t text; begin foreach t in array array['customers','vehicles','repair_orders','inspections','inspection_items','diagnostic_scans','diagnostic_codes','diagnoses','parts','inventory','repair_order_items','estimates','invoices','payments','customer_followups','audit_logs'] loop execute format('drop policy if exists %I on public.%I',t||'_tenant',t); execute format('create policy %I on public.%I for all using(shop_id=public.current_shop_id()) with check(shop_id=public.current_shop_id())',t||'_tenant',t); end loop; end $$;
