import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function hash(token:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)throw new Error("Supabase configuration missing.");const db=createClient(url,service,{auth:{persistSession:false}});
 const body=req.method==="POST"?await req.json().catch(()=>({})):{token:new URL(req.url).searchParams.get("token")};const token=String(body.token||"").trim();if(token.length<32)return json({error:"A valid customer access link is required."},400);
 const tokenHash=await hash(token);const {data:e,error:ee}=await db.from("estimates").select("id,shop_id,repair_order_id,subtotal,parts_total,labor_total,shop_supplies,tax,discount,total,status,customer_approved,approval_date,customer_portal_expires_at").eq("customer_portal_token_hash",tokenHash).maybeSingle();if(ee)throw ee;if(!e)return json({error:"This customer link is invalid or has expired."},404);if(e.customer_portal_expires_at&&new Date(e.customer_portal_expires_at)<new Date())return json({error:"This customer link has expired."},410);
 const {data:ro,error:re}=await db.from("repair_orders").select("id,ro_number,status,customer_id,vehicle_id,customer_concern").eq("id",e.repair_order_id).eq("shop_id",e.shop_id).maybeSingle();if(re)throw re;if(!ro)return json({error:"Repair Order not found."},404);
 const [cust,veh,items]=await Promise.all([db.from("customers").select("first_name,last_name").eq("id",ro.customer_id).maybeSingle(),db.from("vehicles").select("year,make,model,trim,vin,mileage").eq("id",ro.vehicle_id).maybeSingle(),db.from("estimate_items").select("id,item_type,description,part_number,quantity,unit_price,labor_hours,labor_rate,line_total").eq("estimate_id",e.id).order("created_at")]);
 if(cust.error)throw cust.error;if(veh.error)throw veh.error;if(items.error)throw items.error;
 if(req.method==="POST"&&String(body.action)==="approve"){if(e.customer_approved)return json({approved:true,message:"Estimate was already approved.",estimate:e});const now=new Date().toISOString();const {data:updated,error:up}=await db.from("estimates").update({customer_approved:true,approval_date:now,status:"Approved",updated_at:now}).eq("id",e.id).eq("customer_portal_token_hash",tokenHash).select("id,status,customer_approved,approval_date,total").single();if(up)throw up;return json({approved:true,message:"Estimate approved.",estimate:updated});}
 if(req.method==="POST"&&String(body.action)==="decline"){const now=new Date().toISOString();const {data:updated,error:up}=await db.from("estimates").update({status:"Declined",updated_at:now}).eq("id",e.id).eq("customer_portal_token_hash",tokenHash).select("id,status,customer_approved").single();if(up)throw up;return json({approved:false,message:"Estimate declined.",estimate:updated});}
 return json({estimate:{id:e.id,status:e.status,customer_approved:e.customer_approved,approval_date:e.approval_date,subtotal:e.subtotal,parts_total:e.parts_total,labor_total:e.labor_total,shop_supplies:e.shop_supplies,tax:e.tax,discount:e.discount,total:e.total},repair_order:{ro_number:ro.ro_number,status:ro.status,customer_concern:ro.customer_concern},customer:{name:[cust.data?.first_name,cust.data?.last_name].filter(Boolean).join(" ")},vehicle:veh.data,items:items.data||[]});
}catch(err){return json({error:err instanceof Error?err.message:"Customer portal request failed."},500)}});